# Generated by Django 3.0.5 on 2020-04-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200416_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STARTED', 'Started'), ('MIDWAY', 'Midway'), ('COMPLETED', 'Completed')], default='CREATED', max_length=10),
        ),
    ]
